### ISSUE TITLE
meta.yml should reference PyPi  package and not github package, otherwise pip cannot infer the version

### ISSUE THREAD

**Issue by nirvana-msu** [conda-forge/automat-feedstock#1]
The details of the issue are explained [here](https://github.com/ContinuumIO/anaconda-issues/issues/809#issuecomment-336672068)

I believe that in order to address the issue, the package `meta.yml` needs to be changed to reference *PyPi*  package and not *github* package.

**Comment by CJ-Wright** [comment]
Are you interested in fixing this? I can fix this if you want but it might be more instructional if you fix this.
Please feel free to ask for help in this issue and read the [conda-forge docs](https://conda-forge.org/docs/meta.html)
You will need to (on a branch on your fork):
1. Change over to the pypi url (see the [example meta.yml](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L18))
1. Download a copy of the `tar.gz` file
1. Get the new `sha256` by running `sha256sum` on the file and put it in the `meta.yml`
1. Increment the build number by 1
1. Add yourself as a maintainer
1. Create a PR into this repo and ping me when you do

**Comment by nirvana-msu** [comment]
Hey @CJ-Wright, I'm afraid the problem could be more complicated than just the package link. I've summarised my findings in [this comment](https://github.com/ContinuumIO/anaconda-issues/issues/809#issuecomment-336672068). The reason I think it's more complicated is because the build recipe in `anaconda` channel does reference *PyPi* package and yet `pip freeze` still reports incorrect `0.0.0` version. The only conda package that worked for me was [clinicalgraphics/automat](https://anaconda.org/clinicalgraphics/automat), and I even tried comparing the `meta.yml` files between that and the one in `anaconda` channel but I could not figure out what makes one work but not the other...

**Comment by CJ-Wright** [comment]
You could try adding `setuptools_scm` to the build requirements. It may not be building with the needed libraries.

**Comment by nirvana-msu** [comment]
Well if you have a look at the `meta.yml` in [clinicalgraphics/automat](https://anaconda.org/clinicalgraphics/automat) they do no such thing. The only difference I can see is the line `script: python setup.py install --single-version-externally-managed --record=record.txt`. I'm not sure if this makes any difference or why. Either way, I clearly do not have enough knowledge of conda builds or `setuptools_scm` to figure out what's going on...

**Comment by CJ-Wright** [comment]
Note that that recipe doesn't have a build section. The scm package was most likely already in the packaging environment which may have made it not needed during the packaging process?

**Comment by akrherz** [comment]
Just curious of the status of this issue?  When I install `automat` from conda-forge on linux python3.6, I get a resulting file `lib/python3.6/site-packages/Automat-0.0.0-py3.6.egg-info` created, such that packages like twisted can not load
```
pkg_resources.ContextualVersionConflict: (Automat 0.0.0 (/opt/miniconda3/envs/prod/lib/python3.6/site-packages), Requirement.parse('Automat>=0.3.0'), {'Twisted'})
```
